package com.google.android.gms.games;

import android.net.Uri;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.common.internal.safeparcel.a;

/* loaded from: classes.dex */
public class a implements Parcelable.Creator<GameEntity> {
    static void a(GameEntity gameEntity, Parcel parcel, int i) {
        int iD = com.google.android.gms.common.internal.safeparcel.b.d(parcel);
        com.google.android.gms.common.internal.safeparcel.b.a(parcel, 1, gameEntity.getApplicationId(), false);
        com.google.android.gms.common.internal.safeparcel.b.a(parcel, 2, gameEntity.getDisplayName(), false);
        com.google.android.gms.common.internal.safeparcel.b.a(parcel, 3, gameEntity.getPrimaryCategory(), false);
        com.google.android.gms.common.internal.safeparcel.b.a(parcel, 4, gameEntity.getSecondaryCategory(), false);
        com.google.android.gms.common.internal.safeparcel.b.a(parcel, 5, gameEntity.getDescription(), false);
        com.google.android.gms.common.internal.safeparcel.b.a(parcel, 6, gameEntity.getDeveloperName(), false);
        com.google.android.gms.common.internal.safeparcel.b.a(parcel, 7, (Parcelable) gameEntity.getIconImageUri(), i, false);
        com.google.android.gms.common.internal.safeparcel.b.a(parcel, 8, (Parcelable) gameEntity.getHiResImageUri(), i, false);
        com.google.android.gms.common.internal.safeparcel.b.a(parcel, 9, (Parcelable) gameEntity.getFeaturedImageUri(), i, false);
        com.google.android.gms.common.internal.safeparcel.b.a(parcel, 10, gameEntity.isPlayEnabledGame());
        com.google.android.gms.common.internal.safeparcel.b.a(parcel, 11, gameEntity.isInstanceInstalled());
        com.google.android.gms.common.internal.safeparcel.b.a(parcel, 12, gameEntity.getInstancePackageName(), false);
        com.google.android.gms.common.internal.safeparcel.b.c(parcel, 13, gameEntity.getGameplayAclStatus());
        com.google.android.gms.common.internal.safeparcel.b.c(parcel, 14, gameEntity.getAchievementTotalCount());
        com.google.android.gms.common.internal.safeparcel.b.c(parcel, 15, gameEntity.getLeaderboardCount());
        com.google.android.gms.common.internal.safeparcel.b.c(parcel, 1000, gameEntity.i());
        com.google.android.gms.common.internal.safeparcel.b.C(parcel, iD);
    }

    @Override // android.os.Parcelable.Creator
    /* renamed from: n, reason: merged with bridge method [inline-methods] */
    public GameEntity createFromParcel(Parcel parcel) {
        int iF;
        int iF2;
        String strL;
        int iF3;
        String strL2;
        boolean zC;
        String strL3;
        Uri uri;
        Uri uri2;
        Uri uri3;
        boolean zC2;
        String strL4;
        String strL5;
        String strL6;
        int iF4;
        String strL7;
        int iC = com.google.android.gms.common.internal.safeparcel.a.c(parcel);
        int i = 0;
        String str = null;
        String str2 = null;
        String str3 = null;
        String str4 = null;
        String str5 = null;
        String str6 = null;
        Uri uri4 = null;
        Uri uri5 = null;
        Uri uri6 = null;
        boolean z = false;
        boolean z2 = false;
        String str7 = null;
        int i2 = 0;
        int i3 = 0;
        int i4 = 0;
        while (parcel.dataPosition() < iC) {
            int iB = com.google.android.gms.common.internal.safeparcel.a.b(parcel);
            switch (com.google.android.gms.common.internal.safeparcel.a.m(iB)) {
                case 1:
                    int i5 = i4;
                    iF = i;
                    iF2 = i5;
                    int i6 = i2;
                    strL = str2;
                    iF3 = i6;
                    boolean z3 = z2;
                    strL2 = str4;
                    zC = z3;
                    Uri uri7 = uri6;
                    strL3 = str6;
                    uri = uri7;
                    Uri uri8 = uri4;
                    uri2 = uri5;
                    uri3 = uri8;
                    String str8 = str5;
                    zC2 = z;
                    strL4 = str8;
                    String str9 = str3;
                    strL5 = str7;
                    strL6 = str9;
                    iF4 = i3;
                    strL7 = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    break;
                case 2:
                    int i7 = i4;
                    iF = i;
                    iF2 = i7;
                    int i8 = i2;
                    strL = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    iF3 = i8;
                    boolean z4 = z2;
                    strL2 = str4;
                    zC = z4;
                    Uri uri9 = uri6;
                    strL3 = str6;
                    uri = uri9;
                    Uri uri10 = uri4;
                    uri2 = uri5;
                    uri3 = uri10;
                    String str10 = str5;
                    zC2 = z;
                    strL4 = str10;
                    String str11 = str3;
                    strL5 = str7;
                    strL6 = str11;
                    String str12 = str;
                    iF4 = i3;
                    strL7 = str12;
                    break;
                case 3:
                    int i9 = i4;
                    iF = i;
                    iF2 = i9;
                    int i10 = i2;
                    strL = str2;
                    iF3 = i10;
                    boolean z5 = z2;
                    strL2 = str4;
                    zC = z5;
                    Uri uri11 = uri6;
                    strL3 = str6;
                    uri = uri11;
                    Uri uri12 = uri4;
                    uri2 = uri5;
                    uri3 = uri12;
                    String str13 = str5;
                    zC2 = z;
                    strL4 = str13;
                    strL5 = str7;
                    strL6 = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    String str14 = str;
                    iF4 = i3;
                    strL7 = str14;
                    break;
                case 4:
                    int i11 = i4;
                    iF = i;
                    iF2 = i11;
                    int i12 = i2;
                    strL = str2;
                    iF3 = i12;
                    boolean z6 = z2;
                    strL2 = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    zC = z6;
                    Uri uri13 = uri6;
                    strL3 = str6;
                    uri = uri13;
                    Uri uri14 = uri4;
                    uri2 = uri5;
                    uri3 = uri14;
                    String str15 = str5;
                    zC2 = z;
                    strL4 = str15;
                    String str16 = str3;
                    strL5 = str7;
                    strL6 = str16;
                    String str17 = str;
                    iF4 = i3;
                    strL7 = str17;
                    break;
                case 5:
                    int i13 = i4;
                    iF = i;
                    iF2 = i13;
                    int i14 = i2;
                    strL = str2;
                    iF3 = i14;
                    boolean z7 = z2;
                    strL2 = str4;
                    zC = z7;
                    Uri uri15 = uri6;
                    strL3 = str6;
                    uri = uri15;
                    Uri uri16 = uri4;
                    uri2 = uri5;
                    uri3 = uri16;
                    zC2 = z;
                    strL4 = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    String str18 = str3;
                    strL5 = str7;
                    strL6 = str18;
                    String str19 = str;
                    iF4 = i3;
                    strL7 = str19;
                    break;
                case 6:
                    int i15 = i4;
                    iF = i;
                    iF2 = i15;
                    int i16 = i2;
                    strL = str2;
                    iF3 = i16;
                    boolean z8 = z2;
                    strL2 = str4;
                    zC = z8;
                    Uri uri17 = uri6;
                    strL3 = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    uri = uri17;
                    Uri uri18 = uri4;
                    uri2 = uri5;
                    uri3 = uri18;
                    String str20 = str5;
                    zC2 = z;
                    strL4 = str20;
                    String str21 = str3;
                    strL5 = str7;
                    strL6 = str21;
                    String str22 = str;
                    iF4 = i3;
                    strL7 = str22;
                    break;
                case 7:
                    uri2 = uri5;
                    uri3 = (Uri) com.google.android.gms.common.internal.safeparcel.a.a(parcel, iB, Uri.CREATOR);
                    int i17 = i2;
                    strL = str2;
                    iF3 = i17;
                    boolean z9 = z2;
                    strL2 = str4;
                    zC = z9;
                    Uri uri19 = uri6;
                    strL3 = str6;
                    uri = uri19;
                    int i18 = i3;
                    strL7 = str;
                    iF4 = i18;
                    String str23 = str5;
                    zC2 = z;
                    strL4 = str23;
                    String str24 = str3;
                    strL5 = str7;
                    strL6 = str24;
                    int i19 = i4;
                    iF = i;
                    iF2 = i19;
                    break;
                case 8:
                    uri3 = uri4;
                    uri2 = (Uri) com.google.android.gms.common.internal.safeparcel.a.a(parcel, iB, Uri.CREATOR);
                    int i20 = i2;
                    strL = str2;
                    iF3 = i20;
                    boolean z10 = z2;
                    strL2 = str4;
                    zC = z10;
                    Uri uri20 = uri6;
                    strL3 = str6;
                    uri = uri20;
                    int i21 = i4;
                    iF = i;
                    iF2 = i21;
                    String str25 = str5;
                    zC2 = z;
                    strL4 = str25;
                    String str26 = str3;
                    strL5 = str7;
                    strL6 = str26;
                    String str27 = str;
                    iF4 = i3;
                    strL7 = str27;
                    break;
                case 9:
                    strL3 = str6;
                    uri = (Uri) com.google.android.gms.common.internal.safeparcel.a.a(parcel, iB, Uri.CREATOR);
                    int i22 = i2;
                    strL = str2;
                    iF3 = i22;
                    boolean z11 = z2;
                    strL2 = str4;
                    zC = z11;
                    int i23 = i3;
                    strL7 = str;
                    iF4 = i23;
                    Uri uri21 = uri4;
                    uri2 = uri5;
                    uri3 = uri21;
                    String str28 = str5;
                    zC2 = z;
                    strL4 = str28;
                    String str29 = str3;
                    strL5 = str7;
                    strL6 = str29;
                    int i24 = i4;
                    iF = i;
                    iF2 = i24;
                    break;
                case 10:
                    int i25 = i4;
                    iF = i;
                    iF2 = i25;
                    int i26 = i2;
                    strL = str2;
                    iF3 = i26;
                    boolean z12 = z2;
                    strL2 = str4;
                    zC = z12;
                    Uri uri22 = uri6;
                    strL3 = str6;
                    uri = uri22;
                    Uri uri23 = uri4;
                    uri2 = uri5;
                    uri3 = uri23;
                    String str30 = str5;
                    zC2 = com.google.android.gms.common.internal.safeparcel.a.c(parcel, iB);
                    strL4 = str30;
                    String str31 = str3;
                    strL5 = str7;
                    strL6 = str31;
                    String str32 = str;
                    iF4 = i3;
                    strL7 = str32;
                    break;
                case 11:
                    int i27 = i4;
                    iF = i;
                    iF2 = i27;
                    int i28 = i2;
                    strL = str2;
                    iF3 = i28;
                    strL2 = str4;
                    zC = com.google.android.gms.common.internal.safeparcel.a.c(parcel, iB);
                    Uri uri24 = uri6;
                    strL3 = str6;
                    uri = uri24;
                    Uri uri25 = uri4;
                    uri2 = uri5;
                    uri3 = uri25;
                    String str33 = str5;
                    zC2 = z;
                    strL4 = str33;
                    String str34 = str3;
                    strL5 = str7;
                    strL6 = str34;
                    String str35 = str;
                    iF4 = i3;
                    strL7 = str35;
                    break;
                case 12:
                    int i29 = i4;
                    iF = i;
                    iF2 = i29;
                    int i30 = i2;
                    strL = str2;
                    iF3 = i30;
                    boolean z13 = z2;
                    strL2 = str4;
                    zC = z13;
                    Uri uri26 = uri6;
                    strL3 = str6;
                    uri = uri26;
                    Uri uri27 = uri4;
                    uri2 = uri5;
                    uri3 = uri27;
                    String str36 = str5;
                    zC2 = z;
                    strL4 = str36;
                    String str37 = str3;
                    strL5 = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    strL6 = str37;
                    String str38 = str;
                    iF4 = i3;
                    strL7 = str38;
                    break;
                case 13:
                    int i31 = i4;
                    iF = i;
                    iF2 = i31;
                    strL = str2;
                    iF3 = com.google.android.gms.common.internal.safeparcel.a.f(parcel, iB);
                    boolean z14 = z2;
                    strL2 = str4;
                    zC = z14;
                    Uri uri28 = uri6;
                    strL3 = str6;
                    uri = uri28;
                    Uri uri29 = uri4;
                    uri2 = uri5;
                    uri3 = uri29;
                    String str39 = str5;
                    zC2 = z;
                    strL4 = str39;
                    String str40 = str3;
                    strL5 = str7;
                    strL6 = str40;
                    String str41 = str;
                    iF4 = i3;
                    strL7 = str41;
                    break;
                case 14:
                    int i32 = i4;
                    iF = i;
                    iF2 = i32;
                    int i33 = i2;
                    strL = str2;
                    iF3 = i33;
                    boolean z15 = z2;
                    strL2 = str4;
                    zC = z15;
                    Uri uri30 = uri6;
                    strL3 = str6;
                    uri = uri30;
                    Uri uri31 = uri4;
                    uri2 = uri5;
                    uri3 = uri31;
                    String str42 = str5;
                    zC2 = z;
                    strL4 = str42;
                    String str43 = str3;
                    strL5 = str7;
                    strL6 = str43;
                    String str44 = str;
                    iF4 = com.google.android.gms.common.internal.safeparcel.a.f(parcel, iB);
                    strL7 = str44;
                    break;
                case 15:
                    iF = i;
                    iF2 = com.google.android.gms.common.internal.safeparcel.a.f(parcel, iB);
                    int i34 = i2;
                    strL = str2;
                    iF3 = i34;
                    boolean z16 = z2;
                    strL2 = str4;
                    zC = z16;
                    Uri uri32 = uri6;
                    strL3 = str6;
                    uri = uri32;
                    Uri uri33 = uri4;
                    uri2 = uri5;
                    uri3 = uri33;
                    String str45 = str5;
                    zC2 = z;
                    strL4 = str45;
                    String str46 = str3;
                    strL5 = str7;
                    strL6 = str46;
                    String str47 = str;
                    iF4 = i3;
                    strL7 = str47;
                    break;
                case 1000:
                    int i35 = i4;
                    iF = com.google.android.gms.common.internal.safeparcel.a.f(parcel, iB);
                    iF2 = i35;
                    int i36 = i2;
                    strL = str2;
                    iF3 = i36;
                    boolean z17 = z2;
                    strL2 = str4;
                    zC = z17;
                    Uri uri34 = uri6;
                    strL3 = str6;
                    uri = uri34;
                    Uri uri35 = uri4;
                    uri2 = uri5;
                    uri3 = uri35;
                    String str48 = str5;
                    zC2 = z;
                    strL4 = str48;
                    String str49 = str3;
                    strL5 = str7;
                    strL6 = str49;
                    String str50 = str;
                    iF4 = i3;
                    strL7 = str50;
                    break;
                default:
                    com.google.android.gms.common.internal.safeparcel.a.b(parcel, iB);
                    int i37 = i4;
                    iF = i;
                    iF2 = i37;
                    int i38 = i2;
                    strL = str2;
                    iF3 = i38;
                    boolean z18 = z2;
                    strL2 = str4;
                    zC = z18;
                    Uri uri36 = uri6;
                    strL3 = str6;
                    uri = uri36;
                    Uri uri37 = uri4;
                    uri2 = uri5;
                    uri3 = uri37;
                    String str51 = str5;
                    zC2 = z;
                    strL4 = str51;
                    String str52 = str3;
                    strL5 = str7;
                    strL6 = str52;
                    String str53 = str;
                    iF4 = i3;
                    strL7 = str53;
                    break;
            }
            int i39 = iF2;
            i = iF;
            i4 = i39;
            int i40 = iF3;
            str2 = strL;
            i2 = i40;
            boolean z19 = zC;
            str4 = strL2;
            z2 = z19;
            Uri uri38 = uri;
            str6 = strL3;
            uri6 = uri38;
            Uri uri39 = uri3;
            uri5 = uri2;
            uri4 = uri39;
            String str54 = strL4;
            z = zC2;
            str5 = str54;
            String str55 = strL6;
            str7 = strL5;
            str3 = str55;
            String str56 = strL7;
            i3 = iF4;
            str = str56;
        }
        if (parcel.dataPosition() != iC) {
            throw new a.C0003a("Overread allowed size end=" + iC, parcel);
        }
        return new GameEntity(i, str, str2, str3, str4, str5, str6, uri4, uri5, uri6, z, z2, str7, i2, i3, i4);
    }

    @Override // android.os.Parcelable.Creator
    /* renamed from: z, reason: merged with bridge method [inline-methods] */
    public GameEntity[] newArray(int i) {
        return new GameEntity[i];
    }
}
