package com.google.android.gms.internal;

import android.os.Parcel;
import android.os.Parcelable;
import android.support.v4.util.TimeUtils;
import android.support.v7.appcompat.R;
import com.google.android.gms.common.internal.safeparcel.a;
import com.google.android.gms.internal.cc;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

/* loaded from: classes.dex */
public class cd implements Parcelable.Creator<cc> {
    static void a(cc ccVar, Parcel parcel, int i) {
        int iD = com.google.android.gms.common.internal.safeparcel.b.d(parcel);
        Set<Integer> setBH = ccVar.bH();
        if (setBH.contains(1)) {
            com.google.android.gms.common.internal.safeparcel.b.c(parcel, 1, ccVar.i());
        }
        if (setBH.contains(2)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 2, ccVar.getAboutMe(), true);
        }
        if (setBH.contains(3)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 3, (Parcelable) ccVar.cc(), i, true);
        }
        if (setBH.contains(4)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 4, ccVar.getBirthday(), true);
        }
        if (setBH.contains(5)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 5, ccVar.getBraggingRights(), true);
        }
        if (setBH.contains(6)) {
            com.google.android.gms.common.internal.safeparcel.b.c(parcel, 6, ccVar.getCircledByCount());
        }
        if (setBH.contains(7)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 7, (Parcelable) ccVar.cd(), i, true);
        }
        if (setBH.contains(8)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 8, ccVar.getCurrentLocation(), true);
        }
        if (setBH.contains(9)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 9, ccVar.getDisplayName(), true);
        }
        if (setBH.contains(12)) {
            com.google.android.gms.common.internal.safeparcel.b.c(parcel, 12, ccVar.getGender());
        }
        if (setBH.contains(14)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 14, ccVar.getId(), true);
        }
        if (setBH.contains(15)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 15, (Parcelable) ccVar.ce(), i, true);
        }
        if (setBH.contains(16)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 16, ccVar.isPlusUser());
        }
        if (setBH.contains(19)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 19, (Parcelable) ccVar.cf(), i, true);
        }
        if (setBH.contains(18)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 18, ccVar.getLanguage(), true);
        }
        if (setBH.contains(21)) {
            com.google.android.gms.common.internal.safeparcel.b.c(parcel, 21, ccVar.getObjectType());
        }
        if (setBH.contains(20)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 20, ccVar.getNickname(), true);
        }
        if (setBH.contains(23)) {
            com.google.android.gms.common.internal.safeparcel.b.b(parcel, 23, ccVar.ch(), true);
        }
        if (setBH.contains(22)) {
            com.google.android.gms.common.internal.safeparcel.b.b(parcel, 22, ccVar.cg(), true);
        }
        if (setBH.contains(25)) {
            com.google.android.gms.common.internal.safeparcel.b.c(parcel, 25, ccVar.getRelationshipStatus());
        }
        if (setBH.contains(24)) {
            com.google.android.gms.common.internal.safeparcel.b.c(parcel, 24, ccVar.getPlusOneCount());
        }
        if (setBH.contains(27)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 27, ccVar.getUrl(), true);
        }
        if (setBH.contains(26)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 26, ccVar.getTagline(), true);
        }
        if (setBH.contains(29)) {
            com.google.android.gms.common.internal.safeparcel.b.a(parcel, 29, ccVar.isVerified());
        }
        if (setBH.contains(28)) {
            com.google.android.gms.common.internal.safeparcel.b.b(parcel, 28, ccVar.ci(), true);
        }
        com.google.android.gms.common.internal.safeparcel.b.C(parcel, iD);
    }

    @Override // android.os.Parcelable.Creator
    /* renamed from: Y, reason: merged with bridge method [inline-methods] */
    public cc[] newArray(int i) {
        return new cc[i];
    }

    @Override // android.os.Parcelable.Creator
    /* renamed from: y, reason: merged with bridge method [inline-methods] */
    public cc createFromParcel(Parcel parcel) {
        int i;
        boolean z;
        cc.a aVar;
        String str;
        String str2;
        int i2;
        cc.b bVar;
        ArrayList arrayList;
        String str3;
        int i3;
        String str4;
        cc.d dVar;
        String str5;
        cc.c cVar;
        String str6;
        int i4;
        ArrayList arrayList2;
        String str7;
        int i5;
        int i6;
        String str8;
        String str9;
        ArrayList arrayList3;
        String str10;
        int iC = com.google.android.gms.common.internal.safeparcel.a.c(parcel);
        HashSet hashSet = new HashSet();
        int i7 = 0;
        String str11 = null;
        cc.a aVar2 = null;
        String str12 = null;
        String str13 = null;
        int i8 = 0;
        cc.b bVar2 = null;
        String str14 = null;
        String str15 = null;
        int i9 = 0;
        String str16 = null;
        cc.c cVar2 = null;
        boolean zC = false;
        String str17 = null;
        cc.d dVar2 = null;
        String str18 = null;
        int i10 = 0;
        ArrayList arrayList4 = null;
        ArrayList arrayList5 = null;
        int i11 = 0;
        int i12 = 0;
        String str19 = null;
        String str20 = null;
        ArrayList arrayList6 = null;
        boolean z2 = false;
        while (parcel.dataPosition() < iC) {
            int iB = com.google.android.gms.common.internal.safeparcel.a.b(parcel);
            switch (com.google.android.gms.common.internal.safeparcel.a.m(iB)) {
                case 1:
                    int iF = com.google.android.gms.common.internal.safeparcel.a.f(parcel, iB);
                    hashSet.add(1);
                    boolean z3 = z2;
                    i = iF;
                    z = z3;
                    String str21 = str20;
                    aVar = aVar2;
                    str = str21;
                    int i13 = i12;
                    str2 = str13;
                    i2 = i13;
                    ArrayList arrayList7 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList7;
                    int i14 = i10;
                    str3 = str15;
                    i3 = i14;
                    cc.d dVar3 = dVar2;
                    str4 = str16;
                    dVar = dVar3;
                    cc.c cVar3 = cVar2;
                    str5 = str17;
                    cVar = cVar3;
                    int i15 = i9;
                    str6 = str18;
                    i4 = i15;
                    String str22 = str14;
                    arrayList2 = arrayList4;
                    str7 = str22;
                    int i16 = i8;
                    i5 = i11;
                    i6 = i16;
                    String str23 = str12;
                    str8 = str19;
                    str9 = str23;
                    String str24 = str11;
                    arrayList3 = arrayList6;
                    str10 = str24;
                    break;
                case 2:
                    String strL = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    hashSet.add(2);
                    boolean z4 = z2;
                    i = i7;
                    z = z4;
                    String str25 = str20;
                    aVar = aVar2;
                    str = str25;
                    int i17 = i12;
                    str2 = str13;
                    i2 = i17;
                    ArrayList arrayList8 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList8;
                    int i18 = i10;
                    str3 = str15;
                    i3 = i18;
                    cc.d dVar4 = dVar2;
                    str4 = str16;
                    dVar = dVar4;
                    cc.c cVar4 = cVar2;
                    str5 = str17;
                    cVar = cVar4;
                    int i19 = i9;
                    str6 = str18;
                    i4 = i19;
                    String str26 = str14;
                    arrayList2 = arrayList4;
                    str7 = str26;
                    int i20 = i8;
                    i5 = i11;
                    i6 = i20;
                    String str27 = str12;
                    str8 = str19;
                    str9 = str27;
                    arrayList3 = arrayList6;
                    str10 = strL;
                    break;
                case 3:
                    cc.a aVar3 = (cc.a) com.google.android.gms.common.internal.safeparcel.a.a(parcel, iB, cc.a.CREATOR);
                    hashSet.add(3);
                    str = str20;
                    aVar = aVar3;
                    boolean z5 = z2;
                    i = i7;
                    z = z5;
                    int i21 = i12;
                    str2 = str13;
                    i2 = i21;
                    ArrayList arrayList9 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList9;
                    int i22 = i10;
                    str3 = str15;
                    i3 = i22;
                    cc.d dVar5 = dVar2;
                    str4 = str16;
                    dVar = dVar5;
                    cc.c cVar5 = cVar2;
                    str5 = str17;
                    cVar = cVar5;
                    int i23 = i9;
                    str6 = str18;
                    i4 = i23;
                    String str28 = str14;
                    arrayList2 = arrayList4;
                    str7 = str28;
                    int i24 = i8;
                    i5 = i11;
                    i6 = i24;
                    String str29 = str12;
                    str8 = str19;
                    str9 = str29;
                    String str30 = str11;
                    arrayList3 = arrayList6;
                    str10 = str30;
                    break;
                case 4:
                    String strL2 = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    hashSet.add(4);
                    boolean z6 = z2;
                    i = i7;
                    z = z6;
                    String str31 = str20;
                    aVar = aVar2;
                    str = str31;
                    int i25 = i12;
                    str2 = str13;
                    i2 = i25;
                    ArrayList arrayList10 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList10;
                    int i26 = i10;
                    str3 = str15;
                    i3 = i26;
                    cc.d dVar6 = dVar2;
                    str4 = str16;
                    dVar = dVar6;
                    cc.c cVar6 = cVar2;
                    str5 = str17;
                    cVar = cVar6;
                    int i27 = i9;
                    str6 = str18;
                    i4 = i27;
                    String str32 = str14;
                    arrayList2 = arrayList4;
                    str7 = str32;
                    int i28 = i8;
                    i5 = i11;
                    i6 = i28;
                    str8 = str19;
                    str9 = strL2;
                    String str33 = str11;
                    arrayList3 = arrayList6;
                    str10 = str33;
                    break;
                case 5:
                    String strL3 = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    hashSet.add(5);
                    boolean z7 = z2;
                    i = i7;
                    z = z7;
                    String str34 = str20;
                    aVar = aVar2;
                    str = str34;
                    int i29 = i12;
                    str2 = strL3;
                    i2 = i29;
                    ArrayList arrayList11 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList11;
                    int i30 = i10;
                    str3 = str15;
                    i3 = i30;
                    cc.d dVar7 = dVar2;
                    str4 = str16;
                    dVar = dVar7;
                    cc.c cVar7 = cVar2;
                    str5 = str17;
                    cVar = cVar7;
                    int i31 = i9;
                    str6 = str18;
                    i4 = i31;
                    String str35 = str14;
                    arrayList2 = arrayList4;
                    str7 = str35;
                    int i32 = i8;
                    i5 = i11;
                    i6 = i32;
                    String str36 = str12;
                    str8 = str19;
                    str9 = str36;
                    String str37 = str11;
                    arrayList3 = arrayList6;
                    str10 = str37;
                    break;
                case 6:
                    int iF2 = com.google.android.gms.common.internal.safeparcel.a.f(parcel, iB);
                    hashSet.add(6);
                    boolean z8 = z2;
                    i = i7;
                    z = z8;
                    String str38 = str20;
                    aVar = aVar2;
                    str = str38;
                    int i33 = i12;
                    str2 = str13;
                    i2 = i33;
                    ArrayList arrayList12 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList12;
                    int i34 = i10;
                    str3 = str15;
                    i3 = i34;
                    cc.d dVar8 = dVar2;
                    str4 = str16;
                    dVar = dVar8;
                    cc.c cVar8 = cVar2;
                    str5 = str17;
                    cVar = cVar8;
                    int i35 = i9;
                    str6 = str18;
                    i4 = i35;
                    String str39 = str14;
                    arrayList2 = arrayList4;
                    str7 = str39;
                    i5 = i11;
                    i6 = iF2;
                    String str40 = str12;
                    str8 = str19;
                    str9 = str40;
                    String str41 = str11;
                    arrayList3 = arrayList6;
                    str10 = str41;
                    break;
                case 7:
                    cc.b bVar3 = (cc.b) com.google.android.gms.common.internal.safeparcel.a.a(parcel, iB, cc.b.CREATOR);
                    hashSet.add(7);
                    arrayList = arrayList5;
                    bVar = bVar3;
                    String str42 = str20;
                    aVar = aVar2;
                    str = str42;
                    int i36 = i12;
                    str2 = str13;
                    i2 = i36;
                    boolean z9 = z2;
                    i = i7;
                    z = z9;
                    int i37 = i10;
                    str3 = str15;
                    i3 = i37;
                    cc.d dVar9 = dVar2;
                    str4 = str16;
                    dVar = dVar9;
                    cc.c cVar9 = cVar2;
                    str5 = str17;
                    cVar = cVar9;
                    int i38 = i9;
                    str6 = str18;
                    i4 = i38;
                    String str43 = str14;
                    arrayList2 = arrayList4;
                    str7 = str43;
                    int i39 = i8;
                    i5 = i11;
                    i6 = i39;
                    String str44 = str12;
                    str8 = str19;
                    str9 = str44;
                    String str45 = str11;
                    arrayList3 = arrayList6;
                    str10 = str45;
                    break;
                case 8:
                    String strL4 = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    hashSet.add(8);
                    boolean z10 = z2;
                    i = i7;
                    z = z10;
                    String str46 = str20;
                    aVar = aVar2;
                    str = str46;
                    int i40 = i12;
                    str2 = str13;
                    i2 = i40;
                    ArrayList arrayList13 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList13;
                    int i41 = i10;
                    str3 = str15;
                    i3 = i41;
                    cc.d dVar10 = dVar2;
                    str4 = str16;
                    dVar = dVar10;
                    cc.c cVar10 = cVar2;
                    str5 = str17;
                    cVar = cVar10;
                    int i42 = i9;
                    str6 = str18;
                    i4 = i42;
                    arrayList2 = arrayList4;
                    str7 = strL4;
                    int i43 = i8;
                    i5 = i11;
                    i6 = i43;
                    String str47 = str12;
                    str8 = str19;
                    str9 = str47;
                    String str48 = str11;
                    arrayList3 = arrayList6;
                    str10 = str48;
                    break;
                case 9:
                    String strL5 = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    hashSet.add(9);
                    boolean z11 = z2;
                    i = i7;
                    z = z11;
                    String str49 = str20;
                    aVar = aVar2;
                    str = str49;
                    int i44 = i12;
                    str2 = str13;
                    i2 = i44;
                    ArrayList arrayList14 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList14;
                    int i45 = i10;
                    str3 = strL5;
                    i3 = i45;
                    cc.d dVar11 = dVar2;
                    str4 = str16;
                    dVar = dVar11;
                    cc.c cVar11 = cVar2;
                    str5 = str17;
                    cVar = cVar11;
                    int i46 = i9;
                    str6 = str18;
                    i4 = i46;
                    String str50 = str14;
                    arrayList2 = arrayList4;
                    str7 = str50;
                    int i47 = i8;
                    i5 = i11;
                    i6 = i47;
                    String str51 = str12;
                    str8 = str19;
                    str9 = str51;
                    String str52 = str11;
                    arrayList3 = arrayList6;
                    str10 = str52;
                    break;
                case 10:
                case 11:
                case 13:
                case R.styleable.ActionBar_progressBarPadding /* 17 */:
                default:
                    com.google.android.gms.common.internal.safeparcel.a.b(parcel, iB);
                    boolean z12 = z2;
                    i = i7;
                    z = z12;
                    String str53 = str20;
                    aVar = aVar2;
                    str = str53;
                    int i48 = i12;
                    str2 = str13;
                    i2 = i48;
                    ArrayList arrayList15 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList15;
                    int i49 = i10;
                    str3 = str15;
                    i3 = i49;
                    cc.d dVar12 = dVar2;
                    str4 = str16;
                    dVar = dVar12;
                    cc.c cVar12 = cVar2;
                    str5 = str17;
                    cVar = cVar12;
                    int i50 = i9;
                    str6 = str18;
                    i4 = i50;
                    String str54 = str14;
                    arrayList2 = arrayList4;
                    str7 = str54;
                    int i51 = i8;
                    i5 = i11;
                    i6 = i51;
                    String str55 = str12;
                    str8 = str19;
                    str9 = str55;
                    String str56 = str11;
                    arrayList3 = arrayList6;
                    str10 = str56;
                    break;
                case 12:
                    int iF3 = com.google.android.gms.common.internal.safeparcel.a.f(parcel, iB);
                    hashSet.add(12);
                    boolean z13 = z2;
                    i = i7;
                    z = z13;
                    String str57 = str20;
                    aVar = aVar2;
                    str = str57;
                    int i52 = i12;
                    str2 = str13;
                    i2 = i52;
                    ArrayList arrayList16 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList16;
                    int i53 = i10;
                    str3 = str15;
                    i3 = i53;
                    cc.d dVar13 = dVar2;
                    str4 = str16;
                    dVar = dVar13;
                    cc.c cVar13 = cVar2;
                    str5 = str17;
                    cVar = cVar13;
                    str6 = str18;
                    i4 = iF3;
                    String str58 = str14;
                    arrayList2 = arrayList4;
                    str7 = str58;
                    int i54 = i8;
                    i5 = i11;
                    i6 = i54;
                    String str59 = str12;
                    str8 = str19;
                    str9 = str59;
                    String str60 = str11;
                    arrayList3 = arrayList6;
                    str10 = str60;
                    break;
                case 14:
                    String strL6 = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    hashSet.add(14);
                    boolean z14 = z2;
                    i = i7;
                    z = z14;
                    String str61 = str20;
                    aVar = aVar2;
                    str = str61;
                    int i55 = i12;
                    str2 = str13;
                    i2 = i55;
                    ArrayList arrayList17 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList17;
                    int i56 = i10;
                    str3 = str15;
                    i3 = i56;
                    cc.d dVar14 = dVar2;
                    str4 = strL6;
                    dVar = dVar14;
                    cc.c cVar14 = cVar2;
                    str5 = str17;
                    cVar = cVar14;
                    int i57 = i9;
                    str6 = str18;
                    i4 = i57;
                    String str62 = str14;
                    arrayList2 = arrayList4;
                    str7 = str62;
                    int i58 = i8;
                    i5 = i11;
                    i6 = i58;
                    String str63 = str12;
                    str8 = str19;
                    str9 = str63;
                    String str64 = str11;
                    arrayList3 = arrayList6;
                    str10 = str64;
                    break;
                case 15:
                    cc.c cVar15 = (cc.c) com.google.android.gms.common.internal.safeparcel.a.a(parcel, iB, cc.c.CREATOR);
                    hashSet.add(15);
                    str5 = str17;
                    cVar = cVar15;
                    String str65 = str20;
                    aVar = aVar2;
                    str = str65;
                    int i59 = i12;
                    str2 = str13;
                    i2 = i59;
                    ArrayList arrayList18 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList18;
                    int i60 = i10;
                    str3 = str15;
                    i3 = i60;
                    cc.d dVar15 = dVar2;
                    str4 = str16;
                    dVar = dVar15;
                    ArrayList arrayList19 = arrayList6;
                    str10 = str11;
                    arrayList3 = arrayList19;
                    int i61 = i9;
                    str6 = str18;
                    i4 = i61;
                    String str66 = str14;
                    arrayList2 = arrayList4;
                    str7 = str66;
                    int i62 = i8;
                    i5 = i11;
                    i6 = i62;
                    String str67 = str12;
                    str8 = str19;
                    str9 = str67;
                    boolean z15 = z2;
                    i = i7;
                    z = z15;
                    break;
                case 16:
                    zC = com.google.android.gms.common.internal.safeparcel.a.c(parcel, iB);
                    hashSet.add(16);
                    boolean z16 = z2;
                    i = i7;
                    z = z16;
                    String str68 = str20;
                    aVar = aVar2;
                    str = str68;
                    int i63 = i12;
                    str2 = str13;
                    i2 = i63;
                    ArrayList arrayList20 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList20;
                    int i64 = i10;
                    str3 = str15;
                    i3 = i64;
                    cc.d dVar16 = dVar2;
                    str4 = str16;
                    dVar = dVar16;
                    cc.c cVar16 = cVar2;
                    str5 = str17;
                    cVar = cVar16;
                    int i65 = i9;
                    str6 = str18;
                    i4 = i65;
                    String str69 = str14;
                    arrayList2 = arrayList4;
                    str7 = str69;
                    int i66 = i8;
                    i5 = i11;
                    i6 = i66;
                    String str70 = str12;
                    str8 = str19;
                    str9 = str70;
                    String str71 = str11;
                    arrayList3 = arrayList6;
                    str10 = str71;
                    break;
                case R.styleable.ActionBar_itemPadding /* 18 */:
                    String strL7 = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    hashSet.add(18);
                    boolean z17 = z2;
                    i = i7;
                    z = z17;
                    String str72 = str20;
                    aVar = aVar2;
                    str = str72;
                    int i67 = i12;
                    str2 = str13;
                    i2 = i67;
                    ArrayList arrayList21 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList21;
                    int i68 = i10;
                    str3 = str15;
                    i3 = i68;
                    cc.d dVar17 = dVar2;
                    str4 = str16;
                    dVar = dVar17;
                    cc.c cVar17 = cVar2;
                    str5 = strL7;
                    cVar = cVar17;
                    int i69 = i9;
                    str6 = str18;
                    i4 = i69;
                    String str73 = str14;
                    arrayList2 = arrayList4;
                    str7 = str73;
                    int i70 = i8;
                    i5 = i11;
                    i6 = i70;
                    String str74 = str12;
                    str8 = str19;
                    str9 = str74;
                    String str75 = str11;
                    arrayList3 = arrayList6;
                    str10 = str75;
                    break;
                case TimeUtils.HUNDRED_DAY_FIELD_LEN /* 19 */:
                    cc.d dVar18 = (cc.d) com.google.android.gms.common.internal.safeparcel.a.a(parcel, iB, cc.d.CREATOR);
                    hashSet.add(19);
                    str4 = str16;
                    dVar = dVar18;
                    String str76 = str20;
                    aVar = aVar2;
                    str = str76;
                    int i71 = i12;
                    str2 = str13;
                    i2 = i71;
                    ArrayList arrayList22 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList22;
                    int i72 = i10;
                    str3 = str15;
                    i3 = i72;
                    ArrayList arrayList23 = arrayList6;
                    str10 = str11;
                    arrayList3 = arrayList23;
                    cc.c cVar18 = cVar2;
                    str5 = str17;
                    cVar = cVar18;
                    int i73 = i9;
                    str6 = str18;
                    i4 = i73;
                    String str77 = str14;
                    arrayList2 = arrayList4;
                    str7 = str77;
                    int i74 = i8;
                    i5 = i11;
                    i6 = i74;
                    String str78 = str12;
                    str8 = str19;
                    str9 = str78;
                    boolean z18 = z2;
                    i = i7;
                    z = z18;
                    break;
                case 20:
                    String strL8 = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    hashSet.add(20);
                    boolean z19 = z2;
                    i = i7;
                    z = z19;
                    String str79 = str20;
                    aVar = aVar2;
                    str = str79;
                    int i75 = i12;
                    str2 = str13;
                    i2 = i75;
                    ArrayList arrayList24 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList24;
                    int i76 = i10;
                    str3 = str15;
                    i3 = i76;
                    cc.d dVar19 = dVar2;
                    str4 = str16;
                    dVar = dVar19;
                    cc.c cVar19 = cVar2;
                    str5 = str17;
                    cVar = cVar19;
                    int i77 = i9;
                    str6 = strL8;
                    i4 = i77;
                    String str80 = str14;
                    arrayList2 = arrayList4;
                    str7 = str80;
                    int i78 = i8;
                    i5 = i11;
                    i6 = i78;
                    String str81 = str12;
                    str8 = str19;
                    str9 = str81;
                    String str82 = str11;
                    arrayList3 = arrayList6;
                    str10 = str82;
                    break;
                case 21:
                    int iF4 = com.google.android.gms.common.internal.safeparcel.a.f(parcel, iB);
                    hashSet.add(21);
                    boolean z20 = z2;
                    i = i7;
                    z = z20;
                    String str83 = str20;
                    aVar = aVar2;
                    str = str83;
                    int i79 = i12;
                    str2 = str13;
                    i2 = i79;
                    ArrayList arrayList25 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList25;
                    str3 = str15;
                    i3 = iF4;
                    cc.d dVar20 = dVar2;
                    str4 = str16;
                    dVar = dVar20;
                    cc.c cVar20 = cVar2;
                    str5 = str17;
                    cVar = cVar20;
                    int i80 = i9;
                    str6 = str18;
                    i4 = i80;
                    String str84 = str14;
                    arrayList2 = arrayList4;
                    str7 = str84;
                    int i81 = i8;
                    i5 = i11;
                    i6 = i81;
                    String str85 = str12;
                    str8 = str19;
                    str9 = str85;
                    String str86 = str11;
                    arrayList3 = arrayList6;
                    str10 = str86;
                    break;
                case 22:
                    ArrayList arrayListC = com.google.android.gms.common.internal.safeparcel.a.c(parcel, iB, cc.f.CREATOR);
                    hashSet.add(22);
                    boolean z21 = z2;
                    i = i7;
                    z = z21;
                    String str87 = str20;
                    aVar = aVar2;
                    str = str87;
                    int i82 = i12;
                    str2 = str13;
                    i2 = i82;
                    ArrayList arrayList26 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList26;
                    int i83 = i10;
                    str3 = str15;
                    i3 = i83;
                    cc.d dVar21 = dVar2;
                    str4 = str16;
                    dVar = dVar21;
                    cc.c cVar21 = cVar2;
                    str5 = str17;
                    cVar = cVar21;
                    int i84 = i9;
                    str6 = str18;
                    i4 = i84;
                    String str88 = str14;
                    arrayList2 = arrayListC;
                    str7 = str88;
                    int i85 = i8;
                    i5 = i11;
                    i6 = i85;
                    String str89 = str12;
                    str8 = str19;
                    str9 = str89;
                    String str90 = str11;
                    arrayList3 = arrayList6;
                    str10 = str90;
                    break;
                case 23:
                    ArrayList arrayListC2 = com.google.android.gms.common.internal.safeparcel.a.c(parcel, iB, cc.g.CREATOR);
                    hashSet.add(23);
                    boolean z22 = z2;
                    i = i7;
                    z = z22;
                    String str91 = str20;
                    aVar = aVar2;
                    str = str91;
                    int i86 = i12;
                    str2 = str13;
                    i2 = i86;
                    bVar = bVar2;
                    arrayList = arrayListC2;
                    int i87 = i10;
                    str3 = str15;
                    i3 = i87;
                    cc.d dVar22 = dVar2;
                    str4 = str16;
                    dVar = dVar22;
                    cc.c cVar22 = cVar2;
                    str5 = str17;
                    cVar = cVar22;
                    int i88 = i9;
                    str6 = str18;
                    i4 = i88;
                    String str92 = str14;
                    arrayList2 = arrayList4;
                    str7 = str92;
                    int i89 = i8;
                    i5 = i11;
                    i6 = i89;
                    String str93 = str12;
                    str8 = str19;
                    str9 = str93;
                    String str94 = str11;
                    arrayList3 = arrayList6;
                    str10 = str94;
                    break;
                case 24:
                    int iF5 = com.google.android.gms.common.internal.safeparcel.a.f(parcel, iB);
                    hashSet.add(24);
                    boolean z23 = z2;
                    i = i7;
                    z = z23;
                    String str95 = str20;
                    aVar = aVar2;
                    str = str95;
                    int i90 = i12;
                    str2 = str13;
                    i2 = i90;
                    ArrayList arrayList27 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList27;
                    int i91 = i10;
                    str3 = str15;
                    i3 = i91;
                    cc.d dVar23 = dVar2;
                    str4 = str16;
                    dVar = dVar23;
                    cc.c cVar23 = cVar2;
                    str5 = str17;
                    cVar = cVar23;
                    int i92 = i9;
                    str6 = str18;
                    i4 = i92;
                    String str96 = str14;
                    arrayList2 = arrayList4;
                    str7 = str96;
                    int i93 = i8;
                    i5 = iF5;
                    i6 = i93;
                    String str97 = str12;
                    str8 = str19;
                    str9 = str97;
                    String str98 = str11;
                    arrayList3 = arrayList6;
                    str10 = str98;
                    break;
                case 25:
                    int iF6 = com.google.android.gms.common.internal.safeparcel.a.f(parcel, iB);
                    hashSet.add(25);
                    boolean z24 = z2;
                    i = i7;
                    z = z24;
                    String str99 = str20;
                    aVar = aVar2;
                    str = str99;
                    str2 = str13;
                    i2 = iF6;
                    ArrayList arrayList28 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList28;
                    int i94 = i10;
                    str3 = str15;
                    i3 = i94;
                    cc.d dVar24 = dVar2;
                    str4 = str16;
                    dVar = dVar24;
                    cc.c cVar24 = cVar2;
                    str5 = str17;
                    cVar = cVar24;
                    int i95 = i9;
                    str6 = str18;
                    i4 = i95;
                    String str100 = str14;
                    arrayList2 = arrayList4;
                    str7 = str100;
                    int i96 = i8;
                    i5 = i11;
                    i6 = i96;
                    String str101 = str12;
                    str8 = str19;
                    str9 = str101;
                    String str102 = str11;
                    arrayList3 = arrayList6;
                    str10 = str102;
                    break;
                case 26:
                    String strL9 = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    hashSet.add(26);
                    boolean z25 = z2;
                    i = i7;
                    z = z25;
                    String str103 = str20;
                    aVar = aVar2;
                    str = str103;
                    int i97 = i12;
                    str2 = str13;
                    i2 = i97;
                    ArrayList arrayList29 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList29;
                    int i98 = i10;
                    str3 = str15;
                    i3 = i98;
                    cc.d dVar25 = dVar2;
                    str4 = str16;
                    dVar = dVar25;
                    cc.c cVar25 = cVar2;
                    str5 = str17;
                    cVar = cVar25;
                    int i99 = i9;
                    str6 = str18;
                    i4 = i99;
                    String str104 = str14;
                    arrayList2 = arrayList4;
                    str7 = str104;
                    int i100 = i8;
                    i5 = i11;
                    i6 = i100;
                    String str105 = str12;
                    str8 = strL9;
                    str9 = str105;
                    String str106 = str11;
                    arrayList3 = arrayList6;
                    str10 = str106;
                    break;
                case 27:
                    String strL10 = com.google.android.gms.common.internal.safeparcel.a.l(parcel, iB);
                    hashSet.add(27);
                    boolean z26 = z2;
                    i = i7;
                    z = z26;
                    aVar = aVar2;
                    str = strL10;
                    int i101 = i12;
                    str2 = str13;
                    i2 = i101;
                    ArrayList arrayList30 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList30;
                    int i102 = i10;
                    str3 = str15;
                    i3 = i102;
                    cc.d dVar26 = dVar2;
                    str4 = str16;
                    dVar = dVar26;
                    cc.c cVar26 = cVar2;
                    str5 = str17;
                    cVar = cVar26;
                    int i103 = i9;
                    str6 = str18;
                    i4 = i103;
                    String str107 = str14;
                    arrayList2 = arrayList4;
                    str7 = str107;
                    int i104 = i8;
                    i5 = i11;
                    i6 = i104;
                    String str108 = str12;
                    str8 = str19;
                    str9 = str108;
                    String str109 = str11;
                    arrayList3 = arrayList6;
                    str10 = str109;
                    break;
                case 28:
                    ArrayList arrayListC3 = com.google.android.gms.common.internal.safeparcel.a.c(parcel, iB, cc.h.CREATOR);
                    hashSet.add(28);
                    boolean z27 = z2;
                    i = i7;
                    z = z27;
                    String str110 = str20;
                    aVar = aVar2;
                    str = str110;
                    int i105 = i12;
                    str2 = str13;
                    i2 = i105;
                    ArrayList arrayList31 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList31;
                    int i106 = i10;
                    str3 = str15;
                    i3 = i106;
                    cc.d dVar27 = dVar2;
                    str4 = str16;
                    dVar = dVar27;
                    cc.c cVar27 = cVar2;
                    str5 = str17;
                    cVar = cVar27;
                    int i107 = i9;
                    str6 = str18;
                    i4 = i107;
                    String str111 = str14;
                    arrayList2 = arrayList4;
                    str7 = str111;
                    int i108 = i8;
                    i5 = i11;
                    i6 = i108;
                    String str112 = str12;
                    str8 = str19;
                    str9 = str112;
                    String str113 = str11;
                    arrayList3 = arrayListC3;
                    str10 = str113;
                    break;
                case 29:
                    boolean zC2 = com.google.android.gms.common.internal.safeparcel.a.c(parcel, iB);
                    hashSet.add(29);
                    i = i7;
                    z = zC2;
                    String str114 = str20;
                    aVar = aVar2;
                    str = str114;
                    int i109 = i12;
                    str2 = str13;
                    i2 = i109;
                    ArrayList arrayList32 = arrayList5;
                    bVar = bVar2;
                    arrayList = arrayList32;
                    int i110 = i10;
                    str3 = str15;
                    i3 = i110;
                    cc.d dVar28 = dVar2;
                    str4 = str16;
                    dVar = dVar28;
                    cc.c cVar28 = cVar2;
                    str5 = str17;
                    cVar = cVar28;
                    int i111 = i9;
                    str6 = str18;
                    i4 = i111;
                    String str115 = str14;
                    arrayList2 = arrayList4;
                    str7 = str115;
                    int i112 = i8;
                    i5 = i11;
                    i6 = i112;
                    String str116 = str12;
                    str8 = str19;
                    str9 = str116;
                    String str117 = str11;
                    arrayList3 = arrayList6;
                    str10 = str117;
                    break;
            }
            boolean z28 = z;
            i7 = i;
            z2 = z28;
            String str118 = str;
            aVar2 = aVar;
            str20 = str118;
            int i113 = i2;
            str13 = str2;
            i12 = i113;
            ArrayList arrayList33 = arrayList;
            bVar2 = bVar;
            arrayList5 = arrayList33;
            int i114 = i3;
            str15 = str3;
            i10 = i114;
            cc.d dVar29 = dVar;
            str16 = str4;
            dVar2 = dVar29;
            cc.c cVar29 = cVar;
            str17 = str5;
            cVar2 = cVar29;
            int i115 = i4;
            str18 = str6;
            i9 = i115;
            String str119 = str7;
            arrayList4 = arrayList2;
            str14 = str119;
            int i116 = i6;
            i11 = i5;
            i8 = i116;
            String str120 = str9;
            str19 = str8;
            str12 = str120;
            String str121 = str10;
            arrayList6 = arrayList3;
            str11 = str121;
        }
        if (parcel.dataPosition() != iC) {
            throw new a.C0003a("Overread allowed size end=" + iC, parcel);
        }
        return new cc(hashSet, i7, str11, aVar2, str12, str13, i8, bVar2, str14, str15, i9, str16, cVar2, zC, str17, dVar2, str18, i10, arrayList4, arrayList5, i11, i12, str19, str20, arrayList6, z2);
    }
}
