package com.codapayments.sdk.c;

import android.content.Context;
import android.view.LayoutInflater;
import com.adobe.air.wand.connection.WandWebSocket;

/* loaded from: classes.dex */
public final class f {
    public static String A = null;
    public static String B = null;
    public static String C = null;
    public static String D = null;
    public static String E = null;
    public static String F = null;
    public static String G = null;
    public static String H = null;
    public static String I = null;
    public static String J = null;
    public static String K = null;
    private static LayoutInflater L = null;
    private static Context M = null;
    private static String N = "http://droid.codapayments.com/";
    private static String O = null;
    private static boolean P = true;
    private static String Q = null;
    private static String R = null;
    private static String S = null;
    private static String T = null;
    private static String U = null;
    private static int V = 0;
    private static String W = null;
    private static int X = -1;
    private static int Y = -2;
    private static int Z = -3;
    public static String a = null;
    private static String aA = null;
    private static String aB = null;
    private static String aC = null;
    private static String aD = null;
    private static String aE = null;
    private static String aF = null;
    private static String aG = null;
    private static String aH = null;
    private static String aI = null;
    private static String aJ = null;
    private static String aK = null;
    private static String aL = null;
    private static String aM = null;
    private static String aN = null;
    private static int aa = -4;
    private static int ab = -5;
    private static int ac = -6;
    private static int ad = -7;
    private static int ae = -8;
    private static int af = -9;
    private static int ag = -10;
    private static int ah = -11;
    private static int ai = -12;
    private static int aj = -13;
    private static int ak = -14;
    private static int al = -15;
    private static short am = -21;
    private static short an = -22;
    private static short ao = -23;
    private static short ap = -24;
    private static short aq = -25;
    private static short ar = -26;
    private static String as = "/airtime/m/start-txn";
    private static String at = "/airtime/m/input-msisdn";
    private static String au = "/airtime/m/terms-conditions";
    private static String av;
    private static String aw;
    private static String ax;
    private static String ay;
    private static String az;
    public static String b;
    public static String c;
    public static String d;
    public static int e;
    public static int f;
    public static int g;
    public static int h;
    public static int i;
    public static int j;
    public static String k;
    public static String l;
    public static String m;
    public static String n;
    public static String o;
    public static String p;
    public static String q;
    public static String r;
    public static String s;
    public static boolean t;
    public static int u;
    public static String v;
    public static String w;
    public static String x;
    public static String y;
    public static String z;

    static {
        new StringBuilder(String.valueOf(N)).append("airtime/m//begin");
        a = "SMS_SENT";
        b = "SMS_DELIVERED";
        c = "CodaSDK";
        d = "AndroidFunction";
        u = WandWebSocket.Handshake.TIMEOUT_MILLISECONDS;
        v = "CodaSDK";
        w = "DatabaseHandler";
        x = "CodaPay";
        y = "EncryptUtils";
        z = "HttpUtil";
        A = "JSONUtil";
        B = "SMSManager";
        C = "SMSReceiver";
        D = "CodaWeb";
        E = "CodaWebInterface";
        F = "ProcessCompleteTxn";
        G = "ProcessFinit";
        H = "ProcessPay";
        I = "DeviceInfoManager";
        J = "NotifyToMerchantUtil";
        K = "SMSUtil";
    }
}
